repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        files: ^data/(countries|intblocks|schemas)/.*\.yaml$
      - id: check-json
        files: ^data/schemas/.*\.json$
      - id: end-of-file-fixer
        files: ^(scripts|tests)/.*\.py$
      - id: trailing-whitespace
        files: ^(scripts|tests)/.*\.py$
