#!/usr/bin/env python3
"""Generate docs/data-dictionary.md from JSON Schemas.

Run: python scripts/generate_data_dictionary.py
Exit non-zero if --check and the committed file drifts.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = {
    "countries": ROOT / "data" / "schemas" / "countries.schema.json",
    "intblocks": ROOT / "data" / "schemas" / "intblocks.schema.json",
    "blocktypes": ROOT / "data" / "schemas" / "blocktypes.schema.json",
}
OUT = ROOT / "docs" / "data-dictionary.md"


def _type_label(prop: dict) -> str:
    t = prop.get("type")
    if isinstance(t, list):
        return " | ".join(str(x) for x in t)
    if t:
        return str(t)
    if "enum" in prop:
        return "enum"
    if "$ref" in prop:
        return prop["$ref"]
    return "any"


def _enum_note(prop: dict) -> str:
    enums = prop.get("enum")
    if not enums:
        return ""
    shown = ", ".join(f"`{e}`" for e in enums[:12])
    if len(enums) > 12:
        shown += f", … (+{len(enums) - 12})"
    return f" Values: {shown}."


def render_properties(title: str, schema: dict) -> list[str]:
    lines = [f"## {title}", ""]
    required = set(schema.get("required") or [])
    props = schema.get("properties") or {}
    lines.append("| Field | Type | Required | Description |")
    lines.append("|-------|------|----------|-------------|")
    for name, prop in props.items():
        if not isinstance(prop, dict):
            continue
        desc = (prop.get("description") or "").replace("\n", " ").strip()
        desc += _enum_note(prop)
        lines.append(
            f"| `{name}` | {_type_label(prop)} | {'yes' if name in required else ''} | {desc} |"
        )
    lines.append("")
    return lines


def generate() -> str:
    lines = [
        "<!-- Generated by scripts/generate_data_dictionary.py — do not hand-edit. -->",
        "",
        "# Data dictionary",
        "",
        "Field reference generated from JSON Schemas under `data/schemas/`.",
        "For consumption contracts and join keys, see [ai-consumers.md](ai-consumers.md).",
        "",
    ]
    for key, path in SCHEMAS.items():
        if not path.exists():
            continue
        schema = json.loads(path.read_text(encoding="utf-8"))
        lines.extend(render_properties(key, schema))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/data-dictionary.md differs from regenerated content",
    )
    args = parser.parse_args()
    text = generate()
    if args.check:
        existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if existing != text:
            raise SystemExit(f"{OUT.relative_to(ROOT)} is out of date; run scripts/generate_data_dictionary.py")
        print(f"OK: {OUT.relative_to(ROOT)} matches schemas")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
